### ISSUE TITLE
Already initialized constant COUNTRIES

### ISSUE THREAD

**Issue by morgoth** [Shopify/active_utils#43]
After upgradng `active_merchant` to 1.44.1 and adding `offsite_payments` to my Gemfile I'm getting warnings:

```
/home/wojtek/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/active_utils-2.2.3/lib/active_utils/common/country.rb:65: warning: already initialized constant ActiveMerchant::Country::COUNTRIES
/home/wojtek/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activemerchant-1.44.1/lib/active_merchant/country.rb:62: warning: previous definition of COUNTRIES was here
```

As you can see it is defined in both gems:

https://github.com/Shopify/active_merchant/blob/master/lib/active_merchant/country.rb#L67
https://github.com/Shopify/active_utils/blob/master/lib/active_utils/common/country.rb#L65

**Comment by wvanbergen** [comment]
This has been fixed on master, however, this is a breaking change that will be a major release (3.x)
