### ISSUE TITLE
Name clash with ActiveMerchant

### ISSUE THREAD

**Issue by jlaskowski** [Shopify/active_utils#57]
3.0.0 came with bundle install today and I'm now getting this error when loading Rails console:

uninitialized constant ActiveMerchant::Billing::CreditCard::Validateable (NameError)

Seems to be a name clash.

**Comment by wvanbergen** [comment]
Can you send me your entire backtrace?

**Comment by wvanbergen** [comment]
The module is now called `ActiveUtils::Validateable`. 

If this happens somewhere in ActiveMerchant, you may have to bump it to a newer version (bae5e53b4d3e67ce239227382a9715cf05ea4457 or later)

**Comment by jamonholmgren** [comment]
:+1: Thanks, this helped me.

**Comment by unimatrixZxero** [comment]
Helped me as well. Thanks
